In [ ]:
#simple perceptron

In [1]:
#import lib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as mlt

In [2]:
df=pd.read_csv('emails.csv')

In [3]:
df.head()

                       file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

In [4]:
df.isnull()

         file  message
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False
...       ...      ...
517396  False    False
517397  False    False
517398  False    False
517399  False    False
517400  False    False

[517401 rows x 2 columns]

In [5]:
# independent and dependent value

x=df.iloc[: ,0].astype(str)
y=df.iloc[:,1]

In [6]:
#train test split

from sklearn.model_selection import train_test_split
x_test,y_test,x_train,y_train=train_test_split(x,y,random_state=42,test_size=0.2)

In [7]:
x_test

461188                    sturm-f/sent/61.
188056          jones-t/all_documents/982.
475897         taylor-m/all_documents/531.
407113    scott-s/discussion_threads/2350.
316932              mann-k/notes_inbox/17.
                        ...
259178    kitchen-l/_americas/netco_hr/13.
365838            presto-k/sent_items/312.
131932          germany-c/sent_items/1118.
146867          guzman-m/all_documents/19.
121958        geaccone-t/deleted_items/34.
Name: file, Length: 413920, dtype: object

In [8]:
x_train

461188    Message-ID: <20350268.1075857438942.JavaMail.e...
188056    Message-ID: <19748462.1075846933395.JavaMail.e...
475897    Message-ID: <769685.1075859890053.JavaMail.eva...
407113    Message-ID: <12936065.1075863643173.JavaMail.e...
316932    Message-ID: <31294522.1075845896803.JavaMail.e...
                                ...
259178    Message-ID: <18051711.1075840881312.JavaMail.e...
365838    Message-ID: <30145653.1075854837828.JavaMail.e...
131932    Message-ID: <8145314.1075845150150.JavaMail.ev...
146867    Message-ID: <27072313.1075840580998.JavaMail.e...
121958    Message-ID: <15294201.1075859030603.JavaMail.e...
Name: message, Length: 413920, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec=TfidfVectorizer(stop_words='english' ,max_features=3000)
X_train_vec=vec.fit_transform(x_train)
X_test_vec=vec.transform(x_test)

In [15]:
print(X_test_vec.shape)
print(y_train.shape)

(413920, 3000)
(103481,)

In [16]:
#model train
from sklearn.linear_model import Perceptron
p=Perceptron()
p.fit(X_train_vec,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [413920, 103481]